wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.7.16
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1687397213.272621
    t:
      1:
      - 1
      - 5
      - 37
      - 38
      - 41
      - 53
      - 55
      - 60
      2:
      - 1
      - 5
      - 37
      - 38
      - 41
      - 53
      - 55
      - 60
      3:
      - 3
      - 23
      4: 3.7.16
      5: 0.15.4
      8:
      - 5
checkpoint_config:
  desc: null
  value:
    interval: 1
    max_keep_ckpts: 2
class_names:
  desc: null
  value:
  - bed
  - table
  - sofa
  - chair
  - toilet
  - desk
  - dresser
  - night_stand
  - bookshelf
  - bathtub
custom_hooks:
  desc: null
  value:
  - type: EmptyCacheHook
    after_iter: true
data:
  desc: null
  value:
    samples_per_gpu: 16
    workers_per_gpu: 4
    train:
      type: RepeatDataset
      times: 5
      dataset:
        type: SUNRGBDDataset
        modality:
          use_camera: true
          use_lidar: true
        data_root: data/sunrgbd/
        ann_file: data/sunrgbd/sunrgbd_infos_train.pkl
        pipeline:
        - type: LoadPointsFromFile
          coord_type: DEPTH
          shift_height: false
          use_color: true
          load_dim: 6
          use_dim:
          - 0
          - 1
          - 2
          - 3
          - 4
          - 5
        - type: LoadImageFromFile
        - type: LoadAnnotations3D
        - type: Resize
          img_scale:
          - - 1333
            - 480
          - - 1333
            - 504
          - - 1333
            - 528
          - - 1333
            - 552
          - - 1333
            - 576
          - - 1333
            - 600
          multiscale_mode: value
          keep_ratio: true
        - type: Normalize
          mean:
          - 103.53
          - 116.28
          - 123.675
          std:
          - 1.0
          - 1.0
          - 1.0
          to_rgb: false
        - type: Pad
          size_divisor: 32
        - type: PointSample
          num_points: 100000
        - type: RandomFlip3D
          sync_2d: false
          flip_ratio_bev_horizontal: 0.5
          flip_ratio_bev_vertical: 0.0
        - type: GlobalRotScaleTrans
          rot_range:
          - -0.523599
          - 0.523599
          scale_ratio_range:
          - 0.85
          - 1.15
          translation_std:
          - 0.1
          - 0.1
          - 0.1
          shift_height: false
        - type: DefaultFormatBundle3D
          class_names:
          - bed
          - table
          - sofa
          - chair
          - toilet
          - desk
          - dresser
          - night_stand
          - bookshelf
          - bathtub
        - type: Collect3D
          keys:
          - points
          - img
          - gt_bboxes_3d
          - gt_labels_3d
        filter_empty_gt: false
        classes:
        - bed
        - table
        - sofa
        - chair
        - toilet
        - desk
        - dresser
        - night_stand
        - bookshelf
        - bathtub
        box_type_3d: Depth
    val:
      type: SUNRGBDDataset
      modality:
        use_camera: true
        use_lidar: true
      data_root: data/sunrgbd/
      ann_file: data/sunrgbd/sunrgbd_infos_val.pkl
      pipeline:
      - type: LoadPointsFromFile
        coord_type: DEPTH
        shift_height: false
        use_color: true
        load_dim: 6
        use_dim:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
      - type: LoadImageFromFile
      - type: MultiScaleFlipAug3D
        img_scale:
        - 1333
        - 600
        pts_scale_ratio: 1
        flip: false
        transforms:
        - type: Resize
          multiscale_mode: value
          keep_ratio: true
        - type: Normalize
          mean:
          - 103.53
          - 116.28
          - 123.675
          std:
          - 1.0
          - 1.0
          - 1.0
          to_rgb: false
        - type: Pad
          size_divisor: 32
        - type: PointSample
          num_points: 100000
        - type: DefaultFormatBundle3D
          class_names:
          - bed
          - table
          - sofa
          - chair
          - toilet
          - desk
          - dresser
          - night_stand
          - bookshelf
          - bathtub
          with_label: false
        - type: Collect3D
          keys:
          - points
          - img
      classes:
      - bed
      - table
      - sofa
      - chair
      - toilet
      - desk
      - dresser
      - night_stand
      - bookshelf
      - bathtub
      test_mode: true
      box_type_3d: Depth
    test:
      type: SUNRGBDDataset
      modality:
        use_camera: true
        use_lidar: true
      data_root: data/sunrgbd/
      ann_file: data/sunrgbd/sunrgbd_infos_val.pkl
      pipeline:
      - type: LoadPointsFromFile
        coord_type: DEPTH
        shift_height: false
        use_color: true
        load_dim: 6
        use_dim:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
      - type: LoadImageFromFile
      - type: MultiScaleFlipAug3D
        img_scale:
        - 1333
        - 600
        pts_scale_ratio: 1
        flip: false
        transforms:
        - type: Resize
          multiscale_mode: value
          keep_ratio: true
        - type: Normalize
          mean:
          - 103.53
          - 116.28
          - 123.675
          std:
          - 1.0
          - 1.0
          - 1.0
          to_rgb: false
        - type: Pad
          size_divisor: 32
        - type: PointSample
          num_points: 100000
        - type: DefaultFormatBundle3D
          class_names:
          - bed
          - table
          - sofa
          - chair
          - toilet
          - desk
          - dresser
          - night_stand
          - bookshelf
          - bathtub
          with_label: false
        - type: Collect3D
          keys:
          - points
          - img
      classes:
      - bed
      - table
      - sofa
      - chair
      - toilet
      - desk
      - dresser
      - night_stand
      - bookshelf
      - bathtub
      test_mode: true
      box_type_3d: Depth
data_root:
  desc: null
  value: data/sunrgbd/
dataset_type:
  desc: null
  value: SUNRGBDDataset
dist_params:
  desc: null
  value:
    backend: nccl
gpu_ids:
  desc: null
  value:
  - 0
img_norm_cfg:
  desc: null
  value:
    mean:
    - 103.53
    - 116.28
    - 123.675
    std:
    - 1.0
    - 1.0
    - 1.0
    to_rgb: false
load_from:
  desc: null
  value: https://download.openmmlab.com/mmdetection3d/v0.1.0_models/imvotenet/imvotenet_faster_rcnn_r50_fpn_2x4_sunrgbd-3d-10class/imvotenet_faster_rcnn_r50_fpn_2x4_sunrgbd-3d-10class_20210323_173222-cad62aeb.pth
log_config:
  desc: null
  value:
    interval: 50
    hooks:
    - type: TextLoggerHook
    - type: MMDetWandbHook
      init_kwargs:
        project: tr3d-ff
      interval: 4
      log_checkpoint: true
      log_checkpoint_metadata: true
log_level:
  desc: null
  value: INFO
lr_config:
  desc: null
  value:
    policy: step
    warmup: null
    step:
    - 8
    - 11
model:
  desc: null
  value:
    type: TR3DFF3DDetector
    img_backbone:
      type: ResNet
      depth: 50
      num_stages: 4
      out_indices:
      - 0
      - 1
      - 2
      - 3
      frozen_stages: 1
      norm_cfg:
        type: BN
        requires_grad: false
      norm_eval: true
      style: caffe
    img_neck:
      type: FPN
      in_channels:
      - 256
      - 512
      - 1024
      - 2048
      out_channels: 256
      num_outs: 5
    backbone:
      type: MinkFFResNet
      in_channels: 3
      max_channels: 128
      depth: 34
      norm: batch
    neck:
      type: TR3DNeck
      in_channels:
      - 64
      - 128
      - 128
      - 128
      out_channels: 128
    head:
      type: TR3DHead
      in_channels: 128
      n_reg_outs: 8
      n_classes: 10
      voxel_size: 0.01
      assigner:
        type: TR3DAssigner
        top_pts_threshold: 6
        label2level:
        - 1
        - 1
        - 1
        - 0
        - 0
        - 1
        - 0
        - 0
        - 1
        - 0
      bbox_loss:
        type: RotatedIoU3DLoss
        mode: diou
        reduction: none
    voxel_size: 0.01
    train_cfg: {}
    test_cfg:
      nms_pre: 1000
      iou_thr: 0.5
      score_thr: 0.03
n_points:
  desc: null
  value: 100000
optimizer:
  desc: null
  value:
    type: AdamW
    lr: 0.001
    weight_decay: 0.0001
optimizer_config:
  desc: null
  value:
    grad_clip:
      max_norm: 10
      norm_type: 2
resume_from:
  desc: null
  value: null
runner:
  desc: null
  value:
    type: EpochBasedRunner
    max_epochs: 12
test_pipeline:
  desc: null
  value:
  - type: LoadPointsFromFile
    coord_type: DEPTH
    shift_height: false
    use_color: true
    load_dim: 6
    use_dim:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
  - type: LoadImageFromFile
  - type: MultiScaleFlipAug3D
    img_scale:
    - 1333
    - 600
    pts_scale_ratio: 1
    flip: false
    transforms:
    - type: Resize
      multiscale_mode: value
      keep_ratio: true
    - type: Normalize
      mean:
      - 103.53
      - 116.28
      - 123.675
      std:
      - 1.0
      - 1.0
      - 1.0
      to_rgb: false
    - type: Pad
      size_divisor: 32
    - type: PointSample
      num_points: 100000
    - type: DefaultFormatBundle3D
      class_names:
      - bed
      - table
      - sofa
      - chair
      - toilet
      - desk
      - dresser
      - night_stand
      - bookshelf
      - bathtub
      with_label: false
    - type: Collect3D
      keys:
      - points
      - img
train_pipeline:
  desc: null
  value:
  - type: LoadPointsFromFile
    coord_type: DEPTH
    shift_height: false
    use_color: true
    load_dim: 6
    use_dim:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
  - type: LoadImageFromFile
  - type: LoadAnnotations3D
  - type: Resize
    img_scale:
    - - 1333
      - 480
    - - 1333
      - 504
    - - 1333
      - 528
    - - 1333
      - 552
    - - 1333
      - 576
    - - 1333
      - 600
    multiscale_mode: value
    keep_ratio: true
  - type: Normalize
    mean:
    - 103.53
    - 116.28
    - 123.675
    std:
    - 1.0
    - 1.0
    - 1.0
    to_rgb: false
  - type: Pad
    size_divisor: 32
  - type: PointSample
    num_points: 100000
  - type: RandomFlip3D
    sync_2d: false
    flip_ratio_bev_horizontal: 0.5
    flip_ratio_bev_vertical: 0.0
  - type: GlobalRotScaleTrans
    rot_range:
    - -0.523599
    - 0.523599
    scale_ratio_range:
    - 0.85
    - 1.15
    translation_std:
    - 0.1
    - 0.1
    - 0.1
    shift_height: false
  - type: DefaultFormatBundle3D
    class_names:
    - bed
    - table
    - sofa
    - chair
    - toilet
    - desk
    - dresser
    - night_stand
    - bookshelf
    - bathtub
  - type: Collect3D
    keys:
    - points
    - img
    - gt_bboxes_3d
    - gt_labels_3d
voxel_size:
  desc: null
  value: 0.01
work_dir:
  desc: null
  value: work_dirs/tr3d-ff/img_fpn_f
workflow:
  desc: null
  value:
  - - train
    - 1
